<a href="https://colab.research.google.com/github/adamKuzanski/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


**1D array**

In [9]:
x = np.array([1, 3])
print(x)
print(type(x))
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[1 3]
<class 'numpy.ndarray'>
1
(2,)
2
int64


In [10]:
x = np.array([1.3, 2.3, 1.4])
x.dtype

dtype('float64')

2D **Array**

In [14]:
y = np.array([[1,2,3], [-3,-1,-1]])
y

array([[ 1,  2,  3],
       [-3, -1, -1]])

In [17]:
y.shape

(2, 3)

**3D Array**

In [22]:
x = np.array( 
    [
     [[1,2,4], [4,2,1]], 
      [[1,2,3], [9,9,9]] 
     ] 
    )

print(x.ndim)
print(x.shape)

(2, 2, 3)

**Typy danych**

In [26]:
A = np.array([1, 2, 3], dtype='float')
print(A.dtype)

A = np.array([1, 2, 3], dtype='complex')
print(A.dtype)

A = np.array([1.0, 2.2, 3.6], dtype='int')
print(A.dtype)
print(A)

A = np.array([True, False, False], dtype='bool')
print(A.dtype)

A = np.array([24,120,230], dtype=np.uint)
print(A.dtype)

float64
complex128
int64
[1 2 3]
bool
uint64


**Tworzenie Tablic**

In [35]:
np.zeros(shape=(2, 3, 4), dtype='int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [36]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.full(shape=(4,4), fill_value=5, dtype='int')

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(start=10, stop=100, step=0.05)

array([10.  , 10.05, 10.1 , ..., 99.85, 99.9 , 99.95])

In [45]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [53]:
A = np.arange(15)
# A = A.reshape((3,5))
A = A.reshape((3, -1))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Działania na tablicach**

In [55]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [56]:
A + B

array([6, 0, 7, 4])

In [57]:
A - B

array([0, 2, 1, 0])

In [58]:
A * B

array([ 9, -1, 12,  4])

In [59]:
A / 2

array([1.5, 0.5, 2. , 1. ])

In [61]:
A + 3 #doda stałą

array([6, 4, 7, 5])

In [63]:
A + 3*B

array([12, -2, 13,  8])

In [65]:
print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.divide(A, B))


[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [76]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print("Mnożenie element po elemencie")
print(X * Y)
print('\n')

print("Mnożenie macieży")
print(np.dot(X, Y))
print('\n')
print(np.dot(Y, X))
print('\n')
print(X.dot(Y))
print('\n')
print( X @ Y)
print('\n')

Mnożenie element po elemencie
[[6 0]
 [2 0]]


Mnożenie macieży
[[  3   6]
 [-12   0]]


[[ 6 18]
 [-5 -3]]


[[  3   6]
 [-12   0]]


[[  3   6]
 [-12   0]]




Generowanie liczb pseudolosowych

In [0]:
np.random.seed(0)

In [8]:
np.random.randn()

2.240893199201458

In [10]:
np.random.randn(10)

array([ 0.44386323,  0.33367433,  1.49407907, -0.20515826,  0.3130677 ,
       -0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502])

In [12]:
np.random.randn(10, 4)

array([[ 0.17742614, -0.40178094, -1.63019835,  0.46278226],
       [-0.90729836,  0.0519454 ,  0.72909056,  0.12898291],
       [ 1.13940068, -1.23482582,  0.40234164, -0.68481009],
       [-0.87079715, -0.57884966, -0.31155253,  0.05616534],
       [-1.16514984,  0.90082649,  0.46566244, -1.53624369],
       [ 1.48825219,  1.89588918,  1.17877957, -0.17992484],
       [-1.07075262,  1.05445173, -0.40317695,  1.22244507],
       [ 0.20827498,  0.97663904,  0.3563664 ,  0.70657317],
       [ 0.01050002,  1.78587049,  0.12691209,  0.40198936],
       [ 1.8831507 , -1.34775906, -1.270485  ,  0.96939671]])

In [14]:
np.random.rand()

0.42876870094576613

In [16]:
np.random.rand(10, 2)

array([[0.16249293, 0.61555956],
       [0.12381998, 0.84800823],
       [0.80731896, 0.56910074],
       [0.4071833 , 0.069167  ],
       [0.69742877, 0.45354268],
       [0.7220556 , 0.86638233],
       [0.97552151, 0.85580334],
       [0.01171408, 0.35997806],
       [0.72999056, 0.17162968],
       [0.52103661, 0.05433799]])

In [25]:
np.random.randint(10)

1

In [30]:
np.random.randint(low=10, high=101, size=(2, 4))

array([[54, 23, 80, 48],
       [49, 18, 23, 17]])

In [39]:
np.random.choice([4, 2, 4, 6])

4

In [41]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [46]:
data = np.arange(10)
print(data)

np.random.shuffle(data)
print(data)

[0 1 2 3 4 5 6 7 8 9]
[2 8 7 5 6 1 4 9 3 0]


**Podstawowe funkcje z numpy**

In [48]:
np.exp(1) #exponent

2.718281828459045

In [49]:
np.sqrt(9)

3.0

In [53]:
print( np.all([2, 3, 0 ,2]) ) #paczy czy każdy element zwraca true
print( np.any([0, 0, 0, 0]) ) #paczy  czy którykowliek jest true 

False
False


In [59]:
A = np.random.rand(5)
print(A)

max_index = np.argmax(A)
print(f'Max index to {max_index}')

min_index = np.argmin(A)
print(f'Min index to {min_index}')

print("Zwraca indexy od max do min: ", np.argsort(A))

print(np.max(A))
print(np.min(A))
print(np.mean(A))
print(np.median(A))
print(np.std(A))

[0.09654961 0.25613958 0.59193516 0.4764772  0.48793457]
Max index to 2
Min index to 0
Zwraca indexy od max do min:  [0 1 3 4 2]
0.5919351581884497
0.09654960982745808
0.38180722299352554
0.47647720054983067
0.1797461712426575


**Indeksowanie, Wycinanie**

In [71]:
A = np.arange(20)
print(A)

# A[startIndex: endIndex: step]
# A[ :stopIndex]
# A[startIndex: ]

print(A[2])
print(A[2:])
print(A[:2])
print(A[[0,2]])

print(A[-1])


A = A.reshape(4, -1)
print(A)
print("wycina wiersz ", A[0]) #wycina wiersz
print("wycina wiersz ", A[1])

print("wycina kolumne ", A[:, 0]) #wycina kolumne
print("wycina konkret ", A[1,1]) #wytnie konkretny index

print("wycina konkretne ", A[1:3, 2:4]) #wytnie konkretne indexy



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1]
[0 2]
19
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
wycina wiersz  [0 1 2 3 4]
wycina wiersz  [5 6 7 8 9]
wycina kolumne  [ 0  5 10 15]
wycina konkret  6
wycina konkret  [[ 7  8]
 [12 13]]


**Iteracje po tablicach**

In [76]:
for row in A:
  print(row)

print()

for row in A:
  print(row[0])

print()

for row in A.flat: #wyplaszcza cala  tablice do jednego wymiaru
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]

0
5
10
15

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


**Zmiana rozmiaru tablic**

In [82]:
print(A.shape)

A.reshape(5, 4)

A.ravel() #splaszcza do jednego wymiaru

A.T #zmienia kolumne na wiersz i wiersz na kolumne


(4, 5)


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

**Maski logiczne**

In [91]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)

for row in A:
  print(row)

A > 0

# A[A > 5 and A < -5]
np.bitwise_and(A > -5, A < 5)

A[np.bitwise_and(A > -5, A < 5)]

A[np.bitwise_or(A < -5, A > 5)]

[-10.   -9.5  -9.   -8.5]
[-8.  -7.5 -7.  -6.5]
[-6.  -5.5 -5.  -4.5]
[-4.  -3.5 -3.  -2.5]
[-2.  -1.5 -1.  -0.5]
[0.  0.5 1.  1.5]
[2.  2.5 3.  3.5]
[4.  4.5 5.  5.5]
[6.  6.5 7.  7.5]
[8.  8.5 9.  9.5]


array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])