<a href="https://colab.research.google.com/github/adamKuzanski/data-science-bootcamp/blob/master/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Norma wektora, dlugosc wektora**

In [3]:
import numpy as np

v1 = np.array([0, 4])
print('Norma wektora 2D: ', np.linalg.norm(v1))

v2 = np.array([-10, 10, 13])
print('Norma wektora 3D: ', np.linalg.norm(v2))

Norma wektora 2D:  4.0
Norma wektora 3D:  19.209372712298546


**Odleglosc 2 punktow na plaszczyznie lub przestrzeni**

In [5]:
p1 = np.array([3, 0])
p2 = np.array([0, 4])
print('Odleglosc 2 punktow w 2D to: ', np.linalg.norm(p1 - p2)) #odejmowanie tworzzy wektor

p1 = np.array([3, 0, 1])
p2 = np.array([0, 4, 2])
print('Odleglosc 2 punktow w 3D to: ', np.linalg.norm(p1 - p2)) #odejmowanie tworzzy wektor


Odleglosc 2 punktow w 2D to:  5.0
Odleglosc 2 punktow w 3D to:  5.0990195135927845


**Mnozenie macierzy**

In [12]:
#Przyklad 1
X = np.array([[5, 3],  [3, 9]])
Y = np.array([[1], [-1]])

print(X, '\n')
print(Y, '\n')

Z = np.dot(X, Y)
print(Z.shape)
print()
print(Z)


#Przyklad 2
X = np.array([[2, -1, 3], 
              [3, 1, 0]])
Y  = np.array([[2, 1, -1],
               [0, -1, 2],
               [3, 2, 0]])

print(X)
print()
print(Y)

print("Wynik mnożenia:\n", X.dot(Y))

[[5 3]
 [3 9]] 

[[ 1]
 [-1]] 

(2, 1)

[[ 2]
 [-6]]
[[ 2 -1  3]
 [ 3  1  0]]

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]
Wynik mnożenia:
 [[13  9 -4]
 [ 6  2 -1]]


**Wyznacznik Macierzy**

In [15]:
A = np.array([[2,4], [-1, 3]])
round(np.linalg.det(A))

9.999999999999998

**Ślad Macierzy**

In [16]:
A = np.array([[2,4], [-1, 3]])
np.trace(A)

5

**Macierz jednostkowa**

In [21]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

**Macierz odwrotna**

In [26]:
A = np.array([[2, 4], [-1, 3]])
B = np.linalg.inv(A)

np.set_printoptions(precision=4, suppress=True)

print(B)
np.dot(A,B)



[[ 0.3 -0.4]
 [ 0.1  0.2]]


array([[1., 0.],
       [0., 1.]])

**Macierz transponowana** - zamiana wierszy na klumny i kolumny na wiersze


In [29]:
print(A)
B = np.transpose(A)
print(B)
print(A.T)


[[ 2  4]
 [-1  3]]
[[ 2 -1]
 [ 4  3]]
[[ 2 -1]
 [ 4  3]]


## **Rozwiązywanie układów równań**

In [36]:
A = np.array([[2, 4], [1, -1]])
print(A)
B = np.array([[10], [-1]])
print(B)

A_inv = np.linalg.inv(A)
X = A_inv @ B

print(X)

[[ 2  4]
 [ 1 -1]]
[[10]
 [-1]]
[[1.]
 [2.]]
